//! Genesis payload templates for `turingos init`.
//!
//! Templates are kept as Rust string literals (no separate .toml files) so the
//! Phase 6.0/6.1 alpha slice has zero external resource dependencies. Future
//! Phase 6.x slices may evolve these into separate `.toml` files under
//! `src/cli/templates/` if customization grows non-trivial.

/// TRACE_MATRIX FC2-N16: TISR Phase 6.0/6.1 alpha — Lean proof market genesis template.
/// Lean proof market template (REAL-5 / REAL-12 baseline).
pub const GENESIS_PROOF: &str = r#"# TuringOS genesis payload — Proof market template
# Generated by `turingos init --template proof`
#
# TISR Phase 6.0/6.1 alpha scaffold. Edit before running batches.

[meta]
template = "proof"
spec_version = "1.0"

[market]
type = "lean_proof"
default_bounty_micro = 100_000

[budget]
initial_balance_micro = 1_000_000
max_attempts_per_task = 100

# Phase 6.1+: agent role assignments
# Use `turingos role assign --agent <id> --role <role>` once implemented.
# Until then, edit `agent_pubkeys.json` manually and run lean_market for the
# original TB-10 workflow.
#
# [[agents]]
# name = "Agent_solver_0"
# role = "Solver"
# budget_micro = 500_000
# model = "deepseek-v4-flash"
"#;

/// TRACE_MATRIX FC2-N16: TISR Phase 6.0/6.1 alpha — Polymarket event-resolution genesis template.
/// Polymarket event-resolution template.
pub const GENESIS_POLYMARKET: &str = r#"# TuringOS genesis payload — Polymarket template
# Generated by `turingos init --template polymarket`
#
# TISR Phase 6.0/6.1 alpha scaffold. Edit before running batches.

[meta]
template = "polymarket"
spec_version = "1.0"

[market]
type = "polymarket_event"
default_bounty_micro = 100_000

[budget]
initial_balance_micro = 1_000_000

# Phase 6.1+: polymarket event spec
# Until then, use Stage C P-M2..P-M9 helpers in `experiments/minif2f_v4/`.
#
# [[events]]
# event_id = "evt_001"
# outcome = "YES_NO"
# resolution_oracle = "manual"
"#;

/// TRACE_MATRIX FC2-N16: TISR Phase 6.0/6.1 alpha — Multi-agent arena genesis template.
/// Multi-agent arena template (REAL-12 BullTrader / BearTrader / REAL-BCAST-1 Librarian).
pub const GENESIS_MULTI_AGENT: &str = r#"# TuringOS genesis payload — Multi-agent arena template
# Generated by `turingos init --template multi-agent`
#
# TISR Phase 6.0/6.1 alpha scaffold. Edit before running batches.

[meta]
template = "multi-agent"
spec_version = "1.0"

[market]
type = "multi_agent_arena"

[budget]
initial_balance_micro = 1_000_000

# Phase 6.1+: multi-agent role assignments (REAL-5 / REAL-12 style)
# 10 AgentRole variants supported (REAL-5 original 8 + REAL-12 Bull/Bear).
# Until `turingos agent deploy` lands, edit `agent_pubkeys.json` manually
# and bootstrap via experiments/minif2f_v4/src/bin/lean_market.rs.
#
# [[agents]]
# name = "Agent_bull_0"
# role = "BullTrader"
# budget_micro = 500_000
# model = "deepseek-v4-flash"
#
# [[agents]]
# name = "Agent_bear_0"
# role = "BearTrader"
# budget_micro = 500_000
# model = "claude-haiku-4-5"
"#;
