#!/usr/bin/env python3
"""Stub turingos CLI for ST-07: emits malformed stdout 30% of the time."""
import json
import os
import random
import sys

sub = sys.argv[1] if len(sys.argv) > 1 else ""
malform = random.random() < float(os.environ.get("ST07_STUB_MALFORM", "0.30"))

if sub == "task":
    if malform:
        # Garbage that won't parse as a task_id
        sys.stdout.write("ERR: gibberish " + os.urandom(8).hex() + "\n")
        sys.exit(0)
    else:
        task_id = "task_" + os.urandom(8).hex()
        sys.stdout.write(json.dumps({"task_id": task_id, "bounty_cents": 1000}) + "\n")
        sys.exit(0)
else:
    sys.exit(0)
